---
- name: update yum
  hosts: all
  become: yes
  tasks:
    - name: update
      yum:
        name: '*'
        state: latest
        update_cache: yes

- name: Install mysql
  hosts: tag_Service_mysql
  become: yes
  tasks:
    - name: Download MySQL APT repository configuration package
      nsible.builtin.get_url:
        url: https://dev.mysql.com/get/mysql-apt-config_0.8.12-1_all.deb
        dest: /tmp/mysql-apt-config_0.8.12-1_all.deb

    - name: Install MySQL APT repository configuration package
      yum:
        deb: /tmp/mysql-apt-config_0.8.12-1_all.deb
      register: mysql_repo_install    

    - name: install mysql5.7
      yum:
        name:
          - mysql-server-5.7
          - mysql-client-5.7
          - python-mysqldb 
        state: present

- name: install Ngnix
  hosts: tag_Service_ngnix
  tasks:
    - name: Install Nginx
      yum:
        name: nginx=1.17
        state: present

    - name: Start and enable Nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
